# Generated by Django 5.1.3 on 2024-11-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dateOfDeath',
            field=models.DateField(blank=True, null=True),
        ),
    ]
